[package]
name = "hecs"
version = "0.1.6"
description = "A fast, minimal, and ergonomic entity-component-system"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/Ralith/hecs"
readme = "README.md"
keywords = ["ecs", "entity"]
categories = ["data-structures", "game-engines"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true

[features]
# Enables derive(Bundle) and derive(Query)
macros = ["hecs-macros", "once_cell"]

[dependencies]
fxhash = "0.2.1"
parking_lot = "0.10"
lock_api = "0.3.1"
hecs-macros = { path = "macros", version = "0.1.0", optional = true }
once_cell = { version = "1.2", optional = true }

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
required-features = ["macros"]

[profile.release]
debug = true
